Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 8
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git clang cmake libssl-dev

    cd /opt

    # Build rust

    git clone https://github.com/rust-lang/rust.git
    cd rust
    git checkout 717e8831b  # https://github.com/frewsxcv/afl.rs/issues/11
    ./configure --enable-clang --disable-libcpp --enable-optimize --disable-docs
    make -j 8
    cd ..
    echo "PATH=\$PATH:/opt/rust/x86_64-unknown-linux-gnu/stage2/bin" >> ~/.bashrc
    echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/opt/rust/x86_64-unknown-linux-gnu/stage2/lib/" >> ~/.bashrc
    exec bash

    # Build cargo

    git clone https://github.com/rust-lang/cargo
    cd cargo
    apt-get install -y pkg-config  # https://github.com/frewsxcv/afl.rs/issues/11
    git checkout 1ae683a1496be2e35f213e3e11645adcb3ed62b1  # https://github.com/frewsxcv/afl.rs/issues/11
    ./configure --local-rust-root=../rust/x86_64-unknown-linux-gnu/stage2/ --enable-optimize
    make
    make install
    echo "PATH=\$PATH:/opt/cargo/target/x86_64-unknown-linux-gnu/release" >> ~/.bashrc
    exec bash

    # export CXX="$(which clang++) -Wno-c++11-extensions"
    # export LLVM_CONFIG=$(which llvm-config-3.4)
    # build repo with rust plugin
  SHELL
end
